# Generated by Django 5.2.4 on 2025-09-13 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('weight_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Delivery Fee')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Invoice PDF')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Status Changed At')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('gift_item', models.BooleanField(default=False, verbose_name='Gift Item')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
