# Generated by Django 5.2.4 on 2025-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe'), ('amazon_pay', 'Amazon Pay'), ('klarna', 'Klarna'), ('afterpay', 'Afterpay'), ('bitcoin', 'Bitcoin'), ('other_crypto', 'Other Cryptocurrency'), ('alipay', 'Alipay'), ('wechat_pay', 'WeChat Pay'), ('venmo', 'Venmo'), ('square', 'Square'), ('payoneer', 'Payoneer'), ('shop_pay', 'Shop Pay'), ('ideal', 'iDEAL'), ('sofort', 'Sofort'), ('giropay', 'Giropay'), ('boleto', 'Boleto'), ('pix', 'Pix')], default='cod', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Standard Shipping'), ('pickup', 'In-store Pickup'), ('express', 'Express Shipping')], default='standard', max_length=20, verbose_name='Shipping Method'),
        ),
    ]
