# Generated by Django 5.2.4 on 2025-08-24 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='sellers.seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('meeza', 'Meeza'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('installments', 'Installments'), ('bnpl_valu', 'Buy Now Pay Later (valU)'), ('bnpl_tabby', 'Buy Now Pay Later (Tabby)')], default='cod', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
