# Generated by Django 5.2.4 on 2025-09-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_payment_method_remove_order_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_cost',
        ),
    ]
