# Generated by Django 5.2.4 on 2025-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gift_item',
            field=models.BooleanField(default=False, verbose_name='Gift Item'),
        ),
    ]
