# Generated by Django 5.2.4 on 2025-09-14 01:34

import apps.accounts.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('verified', models.BooleanField(default=False, help_text='Designates whether this user has verified their email address.', verbose_name='verified')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', apps.accounts.utils.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_product', 'View Product'), ('view_category', 'View Category'), ('search', 'Search'), ('filter', 'Filter'), ('compare', 'Compare'), ('share', 'Share'), ('add_to_cart', 'Add to Cart'), ('add_to_wishlist', 'Add to Wishlist'), ('view_cart', 'View Cart'), ('view_wishlist', 'View Wishlist'), ('coupon_applied', 'Coupon Applied'), ('coupon_removed', 'Coupon Removed'), ('add_address', 'Add Address'), ('edit_address', 'Edit Address'), ('delete_address', 'Delete Address'), ('set_default_address', 'Set Default Address'), ('checkout', 'Checkout'), ('order_placed', 'Order Placed'), ('order_cancelled', 'Order Cancelled'), ('review', 'Review')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
