# Generated by Django 5.2.4 on 2025-08-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has verified their email address.', verbose_name='verified'),
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
