# Generated by Django 5.2.4 on 2025-08-10 13:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image')),
                ('overall_rating', models.FloatField(default=5.0, verbose_name='Overall Rating')),
                ('available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('trending', models.BooleanField(default=False, help_text='Is this product trending?', verbose_name='Trending')),
                ('in_random_list', models.BooleanField(default=False, verbose_name='Random')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'indexes': [models.Index(fields=['price'], name='price_idx'), models.Index(fields=['overall_rating', 'available'], name='store_produ_overall_148664_idx'), models.Index(fields=['created_at', 'available'], name='store_produ_created_02bc04_idx'), models.Index(fields=['-overall_rating'], name='rating_idx'), models.Index(fields=['available'], name='available_idx'), models.Index(fields=['trending', 'available'], name='available_trending_idx'), models.Index(fields=['in_random_list', 'available'], name='random_trending_idx'), models.Index(fields=['created_at'], name='store_produ_created_5555f3_idx')],
            },
        ),
    ]
