# Generated by Django 5.2.4 on 2025-08-26 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_remove_promotion_apply_to_remove_promotion_brands_and_more'),
        ('sellers', '0002_taxinfo_verified_at_shippingsystem'),
        ('store', '0002_product_price_per_kilogram_product_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='free_shipping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_kilogram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_system',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='sellers.shippingsystem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller'),
        ),
    ]
