# Generated by Django 5.2.4 on 2025-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_free_shipping_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_class',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='ShippingClass',
        ),
    ]
