# Generated by Django 5.2.4 on 2025-08-26 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_remove_coupon_applicable_brands_and_more'),
        ('store', '0003_remove_product_free_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='coupons.coupon'),
        ),
    ]
