# Generated by Django 5.2.4 on 2025-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery',
        ),
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='product_gallery', to='store.productimage'),
        ),
    ]
