# Generated by Django 5.2.4 on 2025-09-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_gallery_product_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=1, null=True, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Review Count'),
        ),
    ]
