# Generated by Django 5.2.4 on 2025-09-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_rating_product_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode: unique product code for scanning and inventory', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit: unique identifier for the product', max_length=100, null=True, unique=True),
        ),
    ]
