# Generated by Django 5.2.4 on 2025-09-01 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address', verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='ShippingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shipping system name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Base shipping fee', max_digits=10)),
                ('per_kg_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee per KG', max_digits=10)),
                ('free_shipping_over', models.DecimalField(blank=True, decimal_places=2, help_text='Free shipping for orders over this amount', max_digits=10, null=True)),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3, help_text='Estimated delivery days')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight allowed (kg)', max_digits=8, null=True)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight allowed (kg)', max_digits=8, null=True)),
                ('supports_cod', models.BooleanField(default=False, help_text='Supports Cash on Delivery')),
                ('international', models.BooleanField(default=False, help_text='Supports international shipping')),
                ('regions', models.TextField(blank=True, help_text='Comma-separated list of supported regions/countries', null=True)),
                ('custom_rules', models.JSONField(blank=True, help_text='Custom rules in JSON format', null=True)),
                ('extra_fees_note', models.CharField(blank=True, help_text='Notes about extra fees or surcharges', max_length=255, null=True)),
                ('active_from', models.DateField(blank=True, help_text='Shipping system active from date', null=True)),
                ('active_until', models.DateField(blank=True, help_text='Shipping system active until date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_systems', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Shipping System',
                'verbose_name_plural': 'Shipping Systems',
            },
        ),
        migrations.CreateModel(
            name='TaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=50, unique=True)),
                ('document', models.FileField(upload_to='tax_docs/')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_info', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Tax Info',
                'verbose_name_plural': 'Tax Infos',
            },
        ),
    ]
