# Generated by Django 5.2.4 on 2025-08-26 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinfo',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShippingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shipping system name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Base shipping fee', max_digits=10)),
                ('per_kg_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee per KG', max_digits=10)),
                ('free_shipping_over', models.DecimalField(blank=True, decimal_places=2, help_text='Free shipping for orders over this amount', max_digits=10, null=True)),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3, help_text='Estimated delivery days')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight allowed (kg)', max_digits=8, null=True)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight allowed (kg)', max_digits=8, null=True)),
                ('supports_cod', models.BooleanField(default=False, help_text='Supports Cash on Delivery')),
                ('international', models.BooleanField(default=False, help_text='Supports international shipping')),
                ('regions', models.TextField(blank=True, help_text='Comma-separated list of supported regions/countries', null=True)),
                ('custom_rules', models.JSONField(blank=True, help_text='Custom rules in JSON format', null=True)),
                ('extra_fees_note', models.CharField(blank=True, help_text='Notes about extra fees or surcharges', max_length=255, null=True)),
                ('active_from', models.DateField(blank=True, help_text='Shipping system active from date', null=True)),
                ('active_until', models.DateField(blank=True, help_text='Shipping system active until date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_systems', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Shipping System',
                'verbose_name_plural': 'Shipping Systems',
            },
        ),
    ]
