# Generated by Django 5.2.4 on 2025-09-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='shipping_system',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingsystem'),
        ),
        migrations.DeleteModel(
            name='ShippingSystem',
        ),
    ]
