# Generated by Django 5.2.4 on 2025-09-20 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('sellers', '0001_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='default_shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping.shippingcompany', verbose_name='Default Shipping Company'),
        ),
        migrations.AddField(
            model_name='seller',
            name='store_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suborder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller'),
        ),
    ]
