# Generated by Django 5.2.4 on 2025-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BXGYConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CouponConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='gift_balance',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_order_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit_per_user',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='value',
        ),
        migrations.RemoveField(
            model_name='couponredemption',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponredemption',
            name='order',
        ),
        migrations.RemoveField(
            model_name='couponredemption',
            name='redeemed_at',
        ),
        migrations.RemoveField(
            model_name='couponredemption',
            name='user',
        ),
    ]
