# Generated by Django 5.2.4 on 2025-08-26 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_initial'),
        ('sellers', '0002_taxinfo_verified_at_shippingsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='seller',
            field=models.OneToOneField(default=-2031, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='sellers.seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('shipping', 'Free Shipping')], default='percentage', max_length=20),
        ),
    ]
