# Generated by Django 5.2.4 on 2025-08-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_seller_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_brands',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_products',
        ),
    ]
