# Generated by Django 5.2.4 on 2025-08-16 15:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points_per_purchase', models.PositiveIntegerField(default=1)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('redemption_ratio', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('min_redemption_points', models.PositiveIntegerField(default=100)),
                ('Eid_multiplier', models.DecimalField(blank=True, decimal_places=2, default=2.0, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('purchases_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('bogo', 'Buy One Get One Free'), ('bxgy', 'Buy X Get Y Free'), ('bxgy_discount', 'Buy X Get Y at Discount'), ('bundle', 'Bundle Discount'), ('free_shipping', 'Free Shipping'), ('gift', 'Gift with Purchase'), ('tiered', 'Tiered Discount')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('max_usage_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, help_text='Buy X quantity', null=True)),
                ('get_quantity', models.PositiveIntegerField(blank=True, help_text='Get Y quantity', null=True)),
                ('get_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('apply_to', models.CharField(choices=[('products', 'Specific Products'), ('categories', 'Entire Categories'), ('all', 'All Products')], default='products', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=1)),
                ('stackable', models.BooleanField(default=False)),
                ('exclusive_group', models.CharField(blank=True, help_text='Promotions in the same group cannot be combined', max_length=50)),
                ('total_uses', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, to='store.category')),
                ('excluded_products', models.ManyToManyField(blank=True, related_name='excluded_promotions', to='store.product')),
                ('gift_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_promotions', to='store.product')),
                ('products', models.ManyToManyField(blank=True, to='store.product')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['discount_type'], name='promotions__discoun_764525_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active'], name='promotions__is_acti_fc6f30_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='promotions__start_d_283aa1_idx'),
        ),
    ]
