# Generated by Django 5.2.4 on 2025-08-22 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('promotions', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(to='store.product'),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='brands',
            field=models.ManyToManyField(blank=True, to='store.brand'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, to='store.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, related_name='excluded_promotions', to='store.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='gift_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_promotions', to='store.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store.tag'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['discount_type'], name='promotions__discoun_764525_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active'], name='promotions__is_acti_fc6f30_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='promotions__start_d_283aa1_idx'),
        ),
    ]
