# Generated by Django 5.2.4 on 2025-09-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('sellers', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bqgpromotion',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bqg_promotions', to='store.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='bqg_promotion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='promotions.bqgpromotion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='sellers.seller'),
        ),
    ]
