# Generated by Django 5.2.4 on 2025-09-05 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_initial'),
        ('store', '0002_rename_price_product_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BQGPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_buy', models.PositiveIntegerField(help_text='Quantity required to activate promotion')),
                ('gift_quantity', models.PositiveIntegerField(help_text='Quantity of free gift')),
                ('percentage_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount on gift (0-100)', max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount applied to total gift price', max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loyaltypoints',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoyaltyProgram',
        ),
        migrations.RemoveField(
            model_name='promotionusage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='promotionusage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='promotionusage',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotionusage',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='promotion',
            name='promotions__discoun_764525_idx',
        ),
        migrations.RemoveIndex(
            model_name='promotion',
            name='promotions__is_acti_fc6f30_idx',
        ),
        migrations.RemoveIndex(
            model_name='promotion',
            name='promotions__start_d_283aa1_idx',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='total_uses',
            new_name='usage_count',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='buy_quantity',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='exclusive_group',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='get_quantity',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='gift_product',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='max_usage',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='max_usage_per_user',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='min_order_value',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='min_quantity',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='stackable',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='users',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='value',
        ),
        migrations.AddField(
            model_name='promotion',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='percentage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, default=2147483647, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='bqgpromotion',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bqg_promotions', to='store.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='bqg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='promotions.bqgpromotion'),
        ),
        migrations.DeleteModel(
            name='LoyaltyPoints',
        ),
        migrations.DeleteModel(
            name='PromotionUsage',
        ),
    ]
