# Generated by Django 5.2.4 on 2025-08-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPromotion',
        ),
    ]
