# Generated by Django 5.2.4 on 2025-08-26 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_delete_productpromotion'),
        ('sellers', '0002_taxinfo_verified_at_shippingsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='apply_to',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='excluded_products',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='products',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='tags',
        ),
        migrations.AddField(
            model_name='promotion',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='sellers.seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('shipping', 'Free Shipping')], max_length=20),
        ),
    ]
