# Generated by Django 5.2.4 on 2025-09-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_bqgpromotion_remove_loyaltypoints_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_discount', models.DecimalField(decimal_places=2, help_text='Percentage shipping discount amount', max_digits=10)),
                ('min_purchase_amount', models.PositiveIntegerField(blank=True, help_text='Minimum purchase amount to qualify for free shipping', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='shipping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='promotions.shippingpromotion'),
        ),
    ]
