# Generated by Django 5.2.4 on 2025-09-08 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_shippingpromotion_promotion_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='shipping',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='bqg',
            new_name='bqg_promotion',
        ),
        migrations.AddField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Discount'), ('bqg', 'Buy X Get Y'), ('shipping', 'Free/Discounted Shipping')], default='', help_text='Type of promotion', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bqgpromotion',
            name='percentage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount on gift (1-100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount (>0)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='percentage_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage discount (1-100)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max number of times this promotion can be used. Null = unlimited.', null=True),
        ),
        migrations.DeleteModel(
            name='ShippingPromotion',
        ),
    ]
