# Generated by Django 5.2.4 on 2025-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_remove_promotion_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Discount'), ('bqg', 'Buy X Get Y')], help_text='Type of promotion', max_length=20),
        ),
    ]
