# Generated by Django 5.2.4 on 2025-09-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shipping system name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Base shipping fee', max_digits=10)),
                ('per_kg_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee per KG', max_digits=10)),
                ('extra_fee_per_distance', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional fee per km/mile (if distance based)', max_digits=10)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight allowed (kg)', max_digits=8, null=True)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight allowed (kg)', max_digits=8, null=True)),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3, help_text='Estimated delivery days')),
                ('max_distance_km', models.PositiveIntegerField(blank=True, help_text='Maximum distance allowed (km)', null=True)),
                ('supported_countries', models.JSONField(blank=True, default=list, help_text='List of supported country codes (ISO alpha-2)')),
                ('supported_regions', models.JSONField(blank=True, default=list, help_text='Optional list of region/state codes (ISO 3166-2)')),
                ('supports_cod', models.BooleanField(default=True, help_text='Supports Cash on Delivery')),
                ('supports_pickup', models.BooleanField(default=False, help_text='Supports customer pickup option')),
                ('tracking_url', models.URLField(blank=True, help_text='Tracking URL template (e.g., https://.../{tracking_number})', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipping System',
                'verbose_name_plural': 'Shipping Systems',
            },
        ),
    ]
