# Generated by Django 5.2.4 on 2025-09-14 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Governorate Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Governorate Name (English)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Governorate Code')),
            ],
            options={
                'verbose_name': 'Governorate',
                'verbose_name_plural': 'Governorates',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='City Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='City Name (English)')),
                ('code', models.CharField(max_length=10, verbose_name='City Code')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='shipping.governorate')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'unique_together': {('governorate', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('full_name', models.CharField(help_text='Full Name', max_length=255, verbose_name='Full Name')),
                ('phone_number', models.CharField(help_text='Primary Phone Number', max_length=20, verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate Phone Number (optional)', max_length=11, verbose_name='Alternate Phone Number (optional)')),
                ('village', models.CharField(blank=True, help_text='Village (optional if you from city center) ', max_length=100, null=True, verbose_name='Village')),
                ('detailed_address', models.CharField(help_text='Write detailed address that you want to deliver the order ', max_length=255, verbose_name='Detailed Address ')),
                ('postal_code', models.CharField(help_text="you can leave it empty if you don't know what postal code", max_length=20, verbose_name='Postal Code')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.city', verbose_name='City')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.governorate', verbose_name='Governorate')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Shipping Company Name')),
                ('company_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shipping_logos/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.address', verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_companies', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shipping Company',
                'verbose_name_plural': 'Shipping Companies',
            },
        ),
        migrations.CreateModel(
            name='ShippingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price')),
                ('estimated_days', models.PositiveIntegerField(verbose_name='Estimated Delivery Days')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='shipping.shippingcompany')),
                ('governorate', models.ManyToManyField(related_name='shipping_plans', to='shipping.governorate')),
            ],
            options={
                'verbose_name': 'Shipping Plan',
                'verbose_name_plural': 'Shipping Plans',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shipping Cost')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Estimated Delivery Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipping.address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingcompany')),
                ('shipping_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingplan')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='WeightPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Weight (kg)')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Weight (kg)')),
                ('price_per_kilo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Kilo (EGP)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_tiers', to='shipping.shippingplan')),
            ],
            options={
                'verbose_name': 'Weight Pricing Tier',
                'verbose_name_plural': 'Weight Pricing Tiers',
                'ordering': ['min_weight'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight (kg)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume (cm³)')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Item',
                'verbose_name_plural': 'Shipment Items',
                'unique_together': {('shipment', 'order_item')},
            },
        ),
    ]
