# Generated by Django 5.2.4 on 2025-09-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='The IP address of the user', null=True, verbose_name='IP Address')),
                ('feedback', models.CharField(blank=True, help_text='Write your feedback here', max_length=255, verbose_name='Review')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='The rating given to the product', verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the review was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the review was last updated', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
