# Generated by Django 5.2.4 on 2025-09-14 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(help_text='The product being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who wrote the review', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('product', 'user'), name='unique_product_review_user'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False), ('user__isnull', True)), fields=('product', 'ip_address'), name='unique_product_review_ip'),
        ),
    ]
