# Generated by Django 5.2.4 on 2025-09-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('store', '0007_product_barcode_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the review was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.CharField(blank=True, help_text='Write your feedback here', max_length=255, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='The IP address of the user', null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(help_text='The product being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='The rating given to the product', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the review was last updated', verbose_name='Updated At'),
        ),
    ]
